### ISSUE TITLE
Docker image pulls

### ISSUE THREAD

**Issue by ayushr2** [illinois-cs241/broadway-grader#9]
We are currently pulling the docker images everytime a student job runs. We might not want to pull each time. As a result, the number of pulls on [Docker Hub](https://hub.docker.com/u/illinois241/) will keep growing a lot with each AG run.

**Comment by bhuvy2** [comment]
+1 to Nick, Download = pull. I think dockerhub can scale to ~400 runs a day (it should be able to handle 400+ runs a second).

Unless we start saturating our networks or greatly increasing latency of jobs, I don't think this is an issue.

**Comment by ayushr2** [comment]
Marking as resolved from the discussion above.

We will want to pull the latest version from DockerHub as we keep updating the image from time to time for bug fixes or extra features. If we want to publish an update will have to iterate over all the worker nodes and build the images.
